### ISSUE TITLE
npm install using node-local-ip-address instead of ip

### ISSUE THREAD

**Issue by mstumpf585** [john-doherty/raspberry-pi-mjpeg-server#2]
After following your readme to install raspberry-pi-mjpeg-server and then runningraspberry-pi-mjpeg-server.js inside nodemodules/raspberry-pi-mjpeg-server directory I get a syntax error inside the node-local-ip-address module. 

After looking around I saw this module is deprecated and it instructed me to us the ip module.  After looking at the latest commit of the file raspberry-pi-mjpeg.js on your repo I saw that you were importing ip. However, on the file I installed on my Rasp pi from npm it is still importing form node-local-ip-address. So maybe something with your npm package needs to updated to reflect the changes made in this repository? Just wanted to make you are aware. 

commands to replicate issue:
```
npm install raspberry-pi-mjpeg-server --save 
cd /nodemodules/raspberry-pi-mjpeg-server
$ node rasberry-pi-mjpeg-server.js -w 1280 -l 1024
```

using raspberry pi zero node version is  0.12.6

**Comment by john-doherty** [comment]
@pro585code thank you for flagging this. I have updated the NPM version which should resolve the issue.
